config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  broadcasts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[new create]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create! message_params

    respond_to do |format|
      format.html { redirect_to @room }
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:room_id, :content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }
    %title ChatterBox
    %meta{ content: "width=device-width,initial-scale=1", name: "viewport" }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = yield :head
    = turbo_include_tags
    = stimulus_include_tags
    = javascript_packs_with_chunks_tag 'application'
    = stylesheet_packs_with_chunks_tag 'application'
  %body
    .container
      = yield

app/views/messages/_message.html.haml
%li.list-group-item.show-tip{ id: "#{dom_id(message)}", "data-bs-toggle" => "tooltip", title: message.created_at.to_s(:short) }
  = message.content

app/views/messages/new.html.haml
%h1 New Message

= turbo_frame_tag "new_message", target: "_top" do
  = form_with(model: [@message.room, @message], data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form|
    .field
      = form.text_field :content
      = form.submit "Send"

= link_to 'Back', @message.room

app/views/rooms/_form.html.haml
= form_with(model: room) do |form|
  - if room.errors.any?
    #error_explanation
      %h2
        = pluralize(room.errors.count, "error")
        prohibited this room from being saved:

      %ul
        - room.errors.each do |error|
          %li= error.full_message

  .field
    = form.label :name
    = form.text_field :name

  .actions
    = form.submit 'Save', class: 'btn btn-success'

app/views/rooms/_room.html.haml
%h1{ id: dom_id(room) }= room.name

app/views/rooms/edit.html.haml
%h1
  Editing: #{@room.name}

= turbo_frame_tag "room" do
  .card.mt-2
    .card-body
      = render 'form', room: @room

= link_to 'Show', @room
|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
%h1 Rooms
%p#notice= notice

%table
  %thead
    %tr
      %th Name
      %th{ colspan: '3' }
  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.name
        %td= link_to 'Show', room
        %td= link_to 'Edit', edit_room_path(room)
        %td= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
%h1 New Room

= render 'form', room: @room
= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
%p#notice= notice

= turbo_stream_from @room

= turbo_frame_tag 'room' do
  .card.mt-2
    .card-body
      = render @room
    .card-footer.text-end
      = link_to 'Edit', edit_room_path(@room), class: 'text-info mx-2'
      = link_to 'Back', rooms_path, "data-turbo-frame": '_top', class: 'text-secondary'

%ul#messages.list-group.mt-3
  = render @room.messages

.card.mt-3
  .card-body.pt-4
    = turbo_frame_tag 'new_message', src: new_room_message_path(@room), target: '_top'